### ISSUE TITLE
Inaccurate and contradictory information about default values

### ISSUE THREAD

**Issue by siliconwaffle** [Whonix/kloak#4]
So in the readme, in kloak -h, and in the manpage, all 3 state that the default maximum delay is 100ms and the default startup timeout is 100ms, when this is just not true. Default max delay is 20ms and default startup timeout is 500ms.

Would also like to add that as far as I can tell the majority of people seem to be under the impression that kloak's default max delay is 200ms, I believe either because it might've used to be 200 or because maybe Whonix's default is 200 or perhaps because the readme quotes some numbers from a KeyTrac demo test, which uses a 200ms delay instead of the default.

Nonetheless, this is kind of a silly oversight when kloak's **only** feature is keystroke delay. I'm not sure if it would be best to correct the kloak -h and readme and manpage, or if it would be best to adjust kloak's defaults to better match the docs, but I do think one of these two routes should be taken.

Line 24 & 25 of src/main.c:
`#define DEFAULT_MAX_DELAY_MS 20      // upper bound on event delay`
`#define DEFAULT_STARTUP_DELAY_MS 500 // wait before grabbing the input device`

Output of kloak -h:
`Usage: kloak [options]`
`Options:`
`  -r filename: device file to read events from. Can specify multiple -r options.`
`  -d delay: maximum delay (milliseconds) of released events. Default 100.`
`  -s startup_timeout: time to wait (milliseconds) before startup. Default 100.`
`  -k csv_string: csv list of rescue key names to exit kloak in case the`
`     keyboard becomes unresponsive. Default is 'KEY_LEFTSHIFT,KEY_RIGHTSHIFT,KEY_ESC'.`
`  -v: verbose mode`

**Comment by ArrayBolt3** [comment]
Looking at the `git blame` output, it almost looks like the change from 100 ms delays to 20 ms delays was an accident committed by Kloak's original author back in 2021. If it wasn't an accident, it most certainly didn't get well documented, and after looking at vmonaco's paper about keystroke obfuscation, I feel that 20 ms is too low. Personally I'm in favor of updating the documentation to reflect the 500 ms delay, but changing the actual keystroke delay back to 100 ms.

@adrelanos does this sound reasonable?

**Comment by adrelanos** [comment]
@claude review
